author = ["Elastic", "Austin Songer"]
description = """
Identifies accounts with a high number of single sign-on (SSO) logon errors. Excessive logon errors may indicate an
attempt to brute force a password or SSO token.
"""
false_positives = [
    """
    Automated processes that attempt to authenticate using expired credentials and unbounded retries may lead to false
    positives.
    """,
]
from = "now-7m"
index = ["filebeat-*", "logs-o365*"]
language = "kuery"
license = "Elastic License v2"
name = "O365 Excessive Single Sign-On Logon Errors"
note = """## Setup

The Office 365 Logs Fleet integration, Filebeat module, or similarly structured data is required to be compatible with this rule."""
risk_score = 71
rule_id = "2de10e77-c144-4e69-afb7-344e7127abd0"
severity = "high"
tags = ["Domain: Cloud", "Data Source: Microsoft 365", "Use Case: Identity and Access Audit", "Tactic: Credential Access", "Managed By: GitHub"]
type = "threshold"
timestamp_override = "event.ingested"
query = '''
event.dataset:o365.audit and event.provider:AzureActiveDirectory and event.category:authentication and o365.audit.LogonError:"SsoArtifactInvalidOrExpired"
'''
enabled = true
interval = "5m"
max_signals = 1
version = 1

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1110"
name = "Brute Force"
reference = "https://attack.mitre.org/techniques/T1110/"


[threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"


[threshold]
field = ["user.id"]
value = 5

[metadata]
creation_date = "2021/05/17"
integration = ["o365"]
maturity = "production"
min_stack_comments = "New fields added: required_fields, related_integrations, setup"
min_stack_version = "8.3.0"
updated_date = "2024/01/05"
managed_by = "GitHub"

